### ISSUE TITLE
Carriage Returns/LFs stripped out of main.js 

### ISSUE THREAD

**Issue by aknisly** [tim-hub/obsidian-bible-reference#232]
I always modify a few things in the main.js to get the specific format that I like. With the most recent update, I'm struggling to find my way around. Somehow almost all the newline/LF's (I'm not sure which?) have been stripped out. I can open a previous version of the file, and the LF's are as expected.

Is there an easy solution? 
Thanks much!
![image](https://github.com/user-attachments/assets/73eb13d6-9356-46f7-8f0e-8ac743834e94)

I've opened this in Meld 3.20.4 and in Neovim 0.6.1 with the same results.

**Comment by tim-hub** [comment]
the `main.js` file is a minified production version, 

So it does not keep the original source code format.

**Comment by tim-hub** [comment]
I will not recommend editing main.js file directly, because you will need to do it again and again for each new release.




If you still want to mofigy the main.js file,

You can build one and change the setting here to non production.

https://github.com/tim-hub/obsidian-bible-reference/blob/df5427aa04a2585f16adb70e5ea3937af89d14a1/scripts/esbuild.config.mjs#L41
